package de.mide.pegsolitaire.model;

import static de.mide.pegsolitaire.model.PlaceStatusEnum.*;

public class Boards {
    public static final PlaceStatusEnum[][] BOARD_CROSS = {
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,SPACE,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED}
    };
    public static final PlaceStatusEnum[][] BOARD_WHEEL = {
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {BLOCKED,PEG,PEG,PEG,PEG,PEG,BLOCKED},
            {PEG,PEG,PEG,SPACE,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {BLOCKED,PEG,PEG,PEG,PEG,PEG,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED}
    };
    public static final PlaceStatusEnum[][] BOARD_EXTENDED_CROSS = {
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,SPACE,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED}
    };
    public static final PlaceStatusEnum[][] BOARD_EXOTIC_CROSS = {
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,SPACE,PEG,PEG,PEG,PEG},
            {PEG,PEG,PEG,PEG,PEG,PEG,PEG,PEG},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED}
    };
    public static final PlaceStatusEnum[][] BOARD_DIAMOND = {
            {BLOCKED,BLOCKED,BLOCKED,BLOCKED,PEG,BLOCKED,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {BLOCKED,PEG,PEG,PEG,PEG,PEG,PEG,PEG,BLOCKED},
            {PEG,PEG,PEG,PEG,SPACE,PEG,PEG,PEG,PEG},
            {BLOCKED,PEG,PEG,PEG,PEG,PEG,PEG,PEG,BLOCKED},
            {BLOCKED,BLOCKED,PEG,PEG,PEG,PEG,PEG,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,PEG,PEG,PEG,BLOCKED,BLOCKED,BLOCKED},
            {BLOCKED,BLOCKED,BLOCKED,BLOCKED,PEG,BLOCKED,BLOCKED,BLOCKED,BLOCKED}
    };
    public static final String BOARD_NAMES[] = new String[]{
            "轮子","拉长十字","异形十字","十字","钻石"
    };
    public static final PlaceStatusEnum[][][] BOARDS = {
            BOARD_WHEEL,BOARD_EXTENDED_CROSS,BOARD_EXOTIC_CROSS,BOARD_CROSS,BOARD_DIAMOND
    };
}
